Update main.yml
Run eval $(minikube -p minikube docker-env)

X Exiting due to ENV_MULTINODE_CONFLICT: The docker-env command is incompatible with multi-node clusters. Use the 'registry' add-on: https://minikube.sigs.k8s.io/docs/handbook/registry/
Error: Process completed with exit code 1.